@startuml WT_CONNECTION_IMPL

struct "__wt_connection_impl" as WT_CONNECTION_IMPL {
    + WT_CONNECTION iface
    __internal session__
    + WT_SESSION_IMPL *default_session
    + WT_SESSION_IMPL dummy_session
    --
    /* Locked: data handle hash array */
    + TAILQ_HEAD(__wt_dhhash, __wt_data_handle) * dhhash;
    /* Locked: data handle list */
    + TAILQ_HEAD(__wt_dhandle_qh, __wt_data_handle) dhqh;
    __
    + WT_FILE_SYSTEM *file_system
    --
    + WT_CACHE *cache
}

note right of WT_CONNECTION_IMPL
    So called "global dhandle list" 
    in https://source.wiredtiger.com/mongodb-6.0/arch-dhandle.html 
    is actually belone to the connection
end note

@enduml