@startuml WT_COL_RLE

struct "__wt_col_rle" as WT_COL_RLE {
    /* Record number of first repeat. */
    + uint64_t recno
    /* Repeat count. */
    + uint64_t rle 
    /* Slot of entry in col_var. */
    + uint32_t indx
}

@enduml