@startuml WT_PAGE_HEADER

struct "__wt_page_header" as WT_PAGE_HEADER {
    
    + uint64_t recno /* 00-07: column-store starting recno */
    + uint64_t write_gen /* 08-15: write generation */
    --
    + uint32_t mem_size /* 16-19: in-memory page size */
    --
    + union {
        uint32_t entries /* 20-23: number of cells on page */
        uint32_t datalen /* 20-23: overflow data length */
    } u
    --
    + uint8_t type /* 24: page type */

    + uint8_t flags                 /* 25: flags */

    /* A byte of padding, positioned to be added to the flags. */
    uint8_t unused /* 26: unused padding */

    uint8_t version           /* 27: version */
}

note top of WT_PAGE_HEADER
    Blocks have a common header, a WT_PAGE_HEADER structure followed by a
    block-manager specific structure.
end note

@enduml